### ISSUE TITLE
Missing Files in `spec-gen/analyzer` Directory

### ISSUE THREAD

**Issue by wupco** [ise-uiuc/KernelGPT#1]
Hello,

```
cd spec-gen/analyzer
make all
```
At this step, it seems that some files are missing(e.g. makefile) in `spec-gen/analyzer`.

**Comment by YangChenyuan** [comment]
Hi, thank you very much for pointing out this issue! We just uploaded the scripts in #2, pls let me know if you have further questions

**Comment by wupco** [comment]
thank you!

**Comment by rousang** [comment]
I have a new problem, when I make all, it said "json.hpp: No such a file or directory".

**Comment by YangChenyuan** [comment]
I just uploaded through #3 , sorry for the mistake

**Comment by rousang** [comment]
thank you very much!

**Comment by rousang** [comment]
Maybe there is still a "clang" folder missing, which is mentioned on lines 5 to 8 of helper.hpp?

**Comment by wupco** [comment]
> Maybe there is still a "clang" folder missing, which is mentioned on lines 5 to 8 of helper.hpp?

Please install ` libclang-dev` first, and could you please open a new issue?
